name: app_flutter
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Version information for your app
version: 1.0.0+1

# Environment SDK version
environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies for your application
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  cupertino_icons: ^1.0.8
  just_audio: any

# Dev dependencies for testing
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter specific configurations
flutter:
  uses-material-design: true
  assets:
    - assets/music/Legends.mp3
    - assets/music/Misfit.mp3
    - assets/music/Lucid_Dreams.mp3
  # Optionally add assets (like images) if you have any
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
